### ISSUE TITLE
Create releases on GitHub

### ISSUE THREAD

**Issue by rammba** [Infiland/TheColorfulCreature#64]
In order to manage live releases easily, we should try to incorporate [releases on GitHub](https://github.com/Infiland/TheColorfulCreature/releases) which will be in sync with Steam releases.

**Comment by Infiland** [comment]
Yes we could, I don't know if it's possible to make an action that automatically uploads the newest releases on Steam, but this is definitely a possibility

**Comment by rammba** [comment]
Even if there if no automatic publish action, having releases here would help to see differences between version.

**Comment by Infiland** [comment]
Added releases in the repo
