### ISSUE TITLE
Steam store page description translation

### ISSUE THREAD

**Issue by rammba** [Infiland/TheColorfulCreature#65]
Currently, Steam description on the Store page is always on English. This can be addressed to support at least same languages as in the game.

Example: 
![image](https://github.com/Infiland/TheColorfulCreature/assets/40705899/9c9e6002-07eb-45c9-9cb1-eac99487f9c4)

**Comment by Infiland** [comment]
Yes, we can have translations on the store page. I can set it up for pretty much any language.

Steam has a way to upload a json file to automatically translate store pages, I will put out a template soon so people could translate. I think we should also translate other store pages (Soundtrack, donation dlcs, bundles)

**Comment by rammba** [comment]
Yes, we can have an option for translation of anything that Steam supports.
