### ISSUE TITLE
Steam store page 'About game' translation

### ISSUE THREAD

**Issue by rammba** [Infiland/TheColorfulCreature#66]
Currently, Steam text on the Store page is always on English. This can be addressed to support at least same languages as in the game.

Example:
![image](https://github.com/Infiland/TheColorfulCreature/assets/40705899/de3b2513-da23-46be-9b04-f8ac96ee1a54)

**Comment by Infiland** [comment]
Translated the about page in all supported languages on steam

**Comment by Infiland** [comment]
Only thing that isn't translated is the images which still have english text, but this could be it's own seperate issue
