### ISSUE TITLE
Better Readme.md

### ISSUE THREAD

**Issue by Infiland** [Infiland/TheColorfulCreature#74]
Improve the look of the repository's readme to be more welcoming and nicer to look at.

**Comment by Sabeer-Junaid** [comment]
hey, I saw that you self-assigned the task to maintain the documentation in the readme.md file. Are you still working on it? If not, may I take care of it?

**Comment by Infiland** [comment]
Yes, absolutely! I've made some changes in the R1.2.0 branch with the readme file, but its still not done which is why it isnt merged with the main branch.

Pretty much I want to make it more clear, with [shields](https://shields.io) as well and make a couple of images for it. It would be much appreciated :)

**Comment by Sabeer-Junaid** [comment]
Great, thank you! I'll review the R1.2.0 branch and work on making it clear, adding shields and images. I'll submit a pull request once it's ready.
